plugins {
    id 'com.android.application'
}

android {
    namespace 'cn.moebai.fuckhyperosotgswitch'
    compileSdk 34

    defaultConfig {
        applicationId "cn.moebai.fuckhyperosotgswitch"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
    compileOnly 'androidx.annotation:annotation:1.7.1'
}
